# Sets up a docker development environment.
version: '3.2'
volumes:
  mongodb:
services:
  www:
    image: jimprov/www:latest
    build: .
    volumes:
      - ./:/app/src/www
    links:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/jimprov
      # NODE_ENV: development
      NODE_ENV: production
    ports:
      - 8000:8000
      - 80:80
    command: nodemon -L

  mongodb:
      image: $MONGO_IMAGE
      stdin_open: true
      tty: true
      volumes:
        - /data/db:/data/db
      ports:
          - 27017:27017
